// Current clan members data
const currentMembers = [
    { id: 1, name: "Apophis", level1: 37, level2: 40, class: "crafter" },
    { id: 2, name: "ExtraLong", level1: 40, level2: 45, class: "Hawkeye" },
    { id: 3, name: "oom", level1: 36, level2: 38, class: "Elven scout" },
    { id: 4, name: "Firefly", level1: 42, level2: 44, class: "Bounty Hunter" },
    { id: 5, name: "Aurora", level1: 38, level2: 41, class: "Elven Wizard" },
    { id: 6, name: "ClameliaDoll", level1: 44, level2: 47, class: "Shillien Elder" },
    { id: 7, name: "Dailily", level1: 45, level2: 47, class: "SPH" },
    { id: 8, name: "RedSky", level1: 37, level2: 41, class: "Cleric" },
    { id: 9, name: "ieP", level1: 36, level2: 36, class: "Shilien Oracle" },
    { id: 10, name: "dissonance", level1: 44, level2: 44, class: "Bishop" },
    { id: 11, name: "Yonko", level1: 22, level2: 27, class: "Cleric" },
    { id: 12, name: "Dyrky", level1: 45, level2: 45, class: "DA" },
    { id: 13, name: "Blu", level1: 46, level2: 48, class: "AW" },
    { id: 14, name: "Dune", level1: 42, level2: 45, class: "Destro" },
    { id: 15, name: "crematE", level1: 35, level2: 41, class: "Human Knight" },
    { id: 16, name: "F4sh10n", level1: 34, level2: 35, class: "Cleric" },
    { id: 17, name: "Mihaela", level1: 38, level2: 40, class: "Spellhowler" },
    { id: 18, name: "TrueBlood", level1: 43, level2: 46, class: "SPH" },
    { id: 19, name: "EdgeA", level1: 41, level2: 44, class: "SPS" },
    { id: 20, name: "dbz", level1: 40, level2: 42, class: "SE" },
    { id: 21, name: "Jimador", level1: 39, level2: 41, class: "Spoiler" },
    { id: 24, name: "Kyra", level1: 26, level2: 27, class: "Shilien Oracle" },
    { id: 25, name: "Nivvy", level1: 24, level2: 24, class: "Elven Oracle" },
    { id: 26, name: "Jalmy", level1: 35, level2: 39, class: "Orc Shaman" },
    { id: 27, name: "ErisMorn", level1: 41, level2: 41, class: "SE" },
    { id: 28, name: "EbonyMaw", level1: 42, level2: 41, class: "Necro" },
    { id: 29, name: "D1nko", level1: 44, level2: 46, class: "TH" },
    { id: 31, name: "En1gma", level1: 38, level2: 40, class: "Shillen Elder" },
    { id: 32, name: "Lami", level1: 31, level2: 35, class: "Human Wizard" },
    { id: 33, name: "EliseWin", level1: 33, level2: 41, class: "Destroyer" },
    { id: 34, name: "Esc0baR", level1: 35, level2: 37, class: "Warrior" },
    { id: 35, name: "Silppuri", level1: 31, level2: 34, class: "Human Knight" },
    { id: 36, name: "Keira", level1: 38, level2: 40, class: "BD" },
    { id: 37, name: "CaptainHog", level1: 28, level2: 30, class: "Dwarf Scavenger" },
    { id: 38, name: "AlinCretu4kk", level1: 43, level2: 47, class: "SWS" },
    { id: 39, name: "UscatulTau", level1: 41, level2: 44, class: "WC" },
    { id: 40, name: "Greven", level1: 40, level2: 42, class: "Destro" },
    { id: 42, name: "Cut", level1: 43, level2: 45, class: "TH" },
    { id: 43, name: "Lukosaur", level1: 33, level2: 33, class: "Rogue" },
    { id: 44, name: "d0ne", level1: 26, level2: 26, class: "Rogue" },
    { id: 45, name: "Sizla", level1: 38, level2: 43, class: "SPH" },
    { id: 46, name: "SuppM8", level1: 36, level2: 42, class: "Prophet" },
    { id: 48, name: "TheCurseD", level1: 38, level2: 38, class: "Human Wizard" },
    { id: 49, name: "DrMajk", level1: 36, level2: 36, class: "Warrior" },
    { id: 50, name: "Darei", level1: 45, level2: 47, class: "Overlord" },
    { id: 51, name: "Rowena", level1: 26, level2: 33, class: "Orc Shaman" },
    { id: 52, name: "Nefertari", level1: 29, level2: 33, class: "Dwarf Scavenger" },
    { id: 53, name: "GlizzyMaxxin", level1: 45, level2: 45, class: "Destro" },
    { id: 54, name: "Cartethyia", level1: 46, level2: 48, class: "SWS" },
    { id: 55, name: "MrIqaros", level1: 30, level2: 35, class: "Rogue" },
    { id: 56, name: "Freydis", level1: 26, level2: 30, class: "Human Wizard" },
    { id: 57, name: "WillowBee", level1: 40, level2: 43, class: "Bishop" },
    { id: 58, name: "Falco", level1: 45, level2: 47, class: "BD" },
    { id: 59, name: "idiapwnz", level1: 44, level2: 47, class: "TH" },
    { id: 61, name: "ManaRefill", level1: 29, level2: 31, class: "Shilien oracle" },
    { id: 63, name: "lovehate", level1: 46, level2: 48, class: "Tyrant" },
    { id: 64, name: "Loyd", level1: 28, level2: 34, class: "DE Wizard" },
    { id: 65, name: "BackBlaze", level1: 20, level2: 24, class: "Human Wizard" },
    { id: 66, name: "DarKeiju", level1: 23, level2: 25, class: "Shilien Oracle" },
    { id: 67, name: "SilverRanger", level1: 42, level2: 45, class: "Silver Ranger" },
    { id: 68, name: "Juontaja", level1: 30, level2: 33, class: "Warrior" },
    { id: 69, name: "Juusto", level1: 35, level2: 38, class: "Palus Knight" },
    { id: 70, name: "Vektra", level1: 34, level2: 41, class: "Warlord" },
    { id: 71, name: "ELLE", level1: 25, level2: 32, class: "Assassin" },
    { id: 72, name: "iInBound", level1: 22, level2: 29, class: "Elven Scout" },
    { id: 73, name: "PaPaRouNa", level1: 23, level2: 25, class: "Cleric" },
    { id: 74, name: "Drac", level1: 32, level2: 37, class: "Rogue" },
    { id: 75, name: "DaughterDater", level1: 35, level2: 36, class: "Palus Knight" },
    { id: 76, name: "Ryoshin", level1: 12, level2: 18, class: "DE Mystic" },
    { id: 77, name: "Haquim", level1: 22, level2: null, class: "Orc Shaman" },
    { id: 78, name: "Teemo", level1: 0, level2: 31, class: "Orc Raider" },
    { id: 79, name: "YellowRanger", level1: 0, level2: 36, class: "Rogue" },
    { id: 80, name: "GoldRanger", level1: 0, level2: 27, class: "Assassin" },
    { id: 81, name: "MrFister", level1: 0, level2: 26, class: "Orc Monk" },
    { id: 82, name: "Avelia", level1: 0, level2: 41, class: "Spoiler" },
    { id: 83, name: "Moj1too", level1: 0, level2: 33, class: "BD" },
    { id: 84, name: "PuffPaff", level1: 0, level2: 35, class: "Elven Scout" },
    { id: 85, name: "RedRanger", level1: 0, level2: 39, class: "Rogue" },
    { id: 86, name: "Kaljakone", level1: 0, level2: 41, class: "Warlock" }
];

// Left clan members data
const leftMembers = [
    { id: 23, name: "Goonezstra", level1: 41, level2: null, class: "SK" },
    { id: 22, name: "Cro", level1: 26, level2: null, class: "Orc Shaman" },
    { id: 30, name: "Gorilla", level1: 27, level2: null, class: "Orc Raider" },
    { id: 41, name: "halFcreaM", level1: 23, level2: null, class: "Elven Wizard" },
    { id: 47, name: "Ferwen", level1: 44, level2: null, class: "Paladin" },
    { id: 60, name: "calipwnz", level1: 44, level2: null, class: "TH" },
    { id: 62, name: "DarkHolt", level1: 42, level2: null, class: "Paladin" }
]; 